version: '3'

services:
  api:
    container_name: api-container
    build: .
    command: yarn dev
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/docbox
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
    ports:
      - "3333:3333"
    links:
      - mongo

  mongo:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/md
    ports:
      - "27017:27017"
